In [1]:
import numpy as np

In [2]:
#Q 
q=np.matrix(np.zeros([6,6]))

In [3]:
#Reward
r= np.matrix([[-1, -1, -1, -1, 0,  -1],
              [-1, -1, -1, 0, -1, 100],
              [-1, -1, -1, 0, -1,  -1],
              [-1,  0,  0,-1,  0,  -1],
              [0,  -1, -1, 0, -1,  100],
              [-1,  0, -1,-1,  0,  100]])

In [7]:
#hyperparameter
gamma =0.8
epsilon =0.4

In [9]:
#the main training loop
for episode in range(101):
    #random inital state
    state =np.random.randint(0,6)
    while (state !=5):
        
        #even in random case we cannot choose actions whose r[state, action]= -1.
        possible_actions =[]
        possible_q=[]
        for action in range(6):
            if r[state,action] >=0:
                possible_actions.append(action)
                possible_q.append(q[state, action])
                
        #step next state,here we use epsilon- greedy algorithm.
        action =-1
        if np.random.random() < epsilon:
            
            #choose random action
            action =possible_actions[np.random.randint(0,len(possible_actions))]
        else:
            
            #greedy 
            action=possible_actions[np.argmax(possible_q)]
            
        #update Q value
        q[state, action] = r[state,action] + gamma* q[action].max()
        
        #go to the next state
        state=action
    
    
    
    #display training progress
    if episode % 10 ==0:
        print("----")
        print("Training episode %d" % episode)
        print (q)

----
Training episode 0
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]
----
Training episode 10
[[  0.    0.    0.    0.    0.    0. ]
 [  0.    0.    0.    0.    0.  100. ]
 [  0.    0.    0.   64.    0.    0. ]
 [  0.   80.    0.    0.   51.2   0. ]
 [  0.    0.    0.   64.    0.    0. ]
 [  0.    0.    0.    0.    0.    0. ]]
----
Training episode 20
[[  0.    0.    0.    0.   80.    0. ]
 [  0.    0.    0.   64.    0.  100. ]
 [  0.    0.    0.   64.    0.    0. ]
 [  0.   80.   51.2   0.   51.2   0. ]
 [  0.    0.    0.   64.    0.  100. ]
 [  0.    0.    0.    0.    0.    0. ]]
----
Training episode 30
[[  0.    0.    0.    0.   80.    0. ]
 [  0.    0.    0.   64.    0.  100. ]
 [  0.    0.    0.   64.    0.    0. ]
 [  0.   80.   51.2   0.   80.    0. ]
 [ 64.    0.    0.   64.    0.  100. ]
 [  0.    0.    0.    0.    0.    0. 